Reaparing size of class window
coders-school/car-dashboard pull request #17
Opened 2024-03-09 15:42 UTC by KrzucH

2024-03-10 19:13 UTC, llisnikowski requested changes
Please rebase branch before merge.

2024-03-10 19:13 UTC, llisnikowski commented on content/MainScreeen.ui.qml
Please change `height: Constants.height / 2` to 'height: Constants.height' and change height in Constants.qml file

2024-03-10 19:13 UTC, llisnikowski commented on content/MenuButton.qml
Maybe it's worth using the Column type here.
https://doc.qt.io/qt-6/qml-qtquick-column.html

2024-03-13 18:29 UTC, dariannax3 commented on content/App.qml
> +            width: parent.width * 0.47
maybe extract width and height, anchors to new file eg. Constrant.qml and define readonly properties there. imo is better  and easer to change values in one place :)
and this 0.47 value will be hidden

2024-03-19 20:20 UTC, llisnikowski approved these changes

2024-03-19 20:44 UTC, llisnikowski commented on content/MenuButton.qml
> +    anchors.centerIn: parent
Move to App.qml

2024-03-19 20:44 UTC, llisnikowski commented on content/MenuButton.qml
>          anchors.topMargin: 175
Use only `anchors.horizontalCenter: parent.horizontalCenter` and `topPadding`, `spacing` properties for column

2024-03-24 04:00 UTC, closed without merging