Gauges control
coders-school/car-dashboard pull request #51
Opened 2024-04-08 20:07 UTC by Macias89-SC

Add speed gauge and fuel level gauge

2024-04-08 20:07 UTC, ziobron commented
@Macias89-SC, we do not have your data in the Coders School database.
1. Please fill in this form https://forms.gle/rkzLsMUSBdnGQgdM9
2. Edit this PR to run this automation once again (you can just add a space in the description or title).
3. Wait one minute. If any label was added to this PR (like Standard, Premium, Podstawy C++, STL) then everything is fine :)
4. If your solution passed, but nothing happens, modify your code (eg. add an empty line) to run the workflow again.

If you don't know what to do - ask on Discord and provide a link to this PR.

2024-04-08 21:02 UTC, KrzucH commented on content/MainBackground.ui.qml
> +Rectangle {
I think we will use same background to all Dashboard.

2024-04-08 21:02 UTC, ziobron commented
Thanks @KrzucH for Code Review.
🏅 1 XP granted

2024-04-11 16:58 UTC, ziobron commented on content/SpeedGauge.ui.qml
> +        Text {
Maybe it's worth to use a RowLayout? https://doc.qt.io/qt-6/qtquicklayouts-index.html

2024-04-11 16:58 UTC, ziobron commented on content/SpeedGauge.ui.qml
> +        */
to be removed?

2024-04-11 16:58 UTC, ziobron commented on content/SpeedGauge.ui.qml
> +        id: text8
ids should be meaningful, like `gauge100Text`

2024-04-17 15:04 UTC, llisnikowski requested changes

2024-04-17 15:04 UTC, llisnikowski commented on content/SpeedGauge.ui.qml
> +        height: 500
Use `anchors.fill: parent`

2024-04-17 15:04 UTC, llisnikowski commented on content/SpeedGauge.ui.qml
> +    Image {
You can use Image as main item

2024-04-24 20:42 UTC, closed without merging